== Creating Quota Files

. Quota files define available browsers for each user. All quota files should be placed to the same directory. 
. For user ```username``` quota file should be named ```username.xml```.
. Each quota file contains the following XML:
+
----
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="firefox" defaultVersion="45.0">
    <version number="45.0">
        <region name="1">
            <host name="host1.example.com" port="4444" count="1"/>
            <host name="host2.example.com" port="4444" count="1"/>
            ...
        </region>
        <region name="2">
            ...
        </region>
    </version>
    <version number="46.0">
        ...
    </version>    
</browser>
<browser name="firefox" defaultVersion="45.0">
    ...
</browser>
...
</qa:browsers>
----
+
Here we define a list of browser names, their versions and default version for each browser. Each version has one or more regions (in cloud term, i.e. data centers). Every region contains one or more hosts. Each host defined in XML should have Selenium listening on specified port. The XML namespace is needed to be fully compatible with http://github.com/seleniumkit/gridrouter[original] Java GridRouter implementation.

=== Proxying VNC Traffic

Sometimes for debugging purposes you need to see the screen of the browser where your test is being executed. The simplest way to do that is to install a https://en.wikipedia.org/wiki/Virtual_Network_Computing[VNC] server to browser host. Default TCP port for VNC protocol is `5900`. Ggr can proxy the VNC traffic from multiple hosts and makes it accessible on a https://en.wikipedia.org/wiki/WebSocket[WebSocket]. For example having the running session ID you can get the VNC traffic by accessing the following endpoint:

.Typical VNC traffic URL
----
ws://ggr-host.example.com:4444/vnc/<session-id>
----
Browser VNC clients like https://github.com/novnc/noVNC[noVNC] work with such URLs out of the box. By default having an XML host entry like this...
    
    <host name="host1.example.com" port="4444" count="1"/>

...Ggr proxies all traffic from `host1.example.com:5900`. You can customize this by adding an optional `vnc` attribute to a host:
    
    <host name="host1.example.com" port="4444" count="1" vnc="vnc://host1.example.com:6900"/>

Two notations are supported in `vnc` attribute:

. If the remote server has a VNC server listening on dedicated TCP port you should use `vnc://` protocol and specify only host and port:
+
    vnc://my-vnc-host.example.com:5900

. If the remote server also returns VNC traffic on a web socket (which is a case for http://aerokube.com/selenoid/latest/#_live_browser_screen[Selenoid]) - then you should specify a `ws://` URL without trailing `<session-id>` value:
+
    ws://my-selenoid-host.example.com/vnc
+
Having this URL Ggr will append session ID and proxy VNC traffic from:
+
    ws://my-selenoid-host.example.com/vnc/<session-id>

=== Working with External Selenium Services

Although Ggr is mainly used for creating your own Selenium cluster you can also configure it to obtain some browsers in external Selenium services such as http://saucelabs.com/[Saucelabs], http://browserstack.com/[BrowserStack] or https://testingbot.com/[TestingBot]. These services always require username and password to be specified. Credentials should be set for each browser version in respective quota file:
----
<qa:browsers xmlns:qa="urn:config.gridrouter.qatools.ru">
<browser name="firefox" defaultVersion="45.0">
    <version number="45.0">
        <region name="1">
            <host name="hub.browserstack.com" port="443" count="1" username="test-user" password="my-password" scheme="https" />
        </region>
    </version>
</browser>
</qa:browsers>
----

=== Guest Quota

By default every quota file corresponds to a user. In some cases you may need to give anonymous (guest) access to some users. This is very useful to maintain a sandbox where users can debug their tests without disturbing other tests. Guest quota is enabled using Ggr flags:

    $ ./ggr -guests-allowed -guest-quota test <the-rest-of-the-flags...>

With these flags specified any browsers declared in `test.xml` file will be accessible without password.